### ISSUE TITLE
Choice of setting up client or server or both

### ISSUE THREAD

**Issue by faribauc** [amimaro/generator-angular-api#6]
Hi,

I just started testing this project and I have to admit it's pretty cool. This is more of a suggestion than an issue though.

I already have an angular project for the frontend and while setting this up, I thought that it might be nice to have the option to generate either only the client of the server code, or both. In my case, I want to keep my frontend/backend repos separate, so I don't need all the client-related code. Anyway, just a thought.

Keep up the good work!

Chris

**Comment by amimaro** [comment]
Thanks for the feedback, Chris!
